### ISSUE TITLE
error loading activities

### ISSUE THREAD

**Issue by deanso** [owncloud/activity#419]
### Steps to reproduce
1. run oc 8.1.3
2. migrate to 8.3
3. go to files
3. click on activities icon of an folder.

### Expected behaviour
Should show me the activities of that folder.

### Actual behaviour
It gives me a loading ring and a yellow box saying: "error loading activities"

If I click on a single file the message goed away. If I disable the activities app and re-enable it, the yellow exclamation box is back.

### Server configuration
**Operating system**: 
Centos 6.7

**Web server:** 
Apache

**Database:** 
MySql

**PHP version:** 
5.4

**ownCloud version:** (see ownCloud admin page)
8.2

**Updated from an older ownCloud or fresh install:**
Just updated from 7.1.3

**List of activated apps:**
 Activity 2.0.2
Deleted files 0.6.3
First Run Wizard 1.1
Full Text Search 0.6.0
PDF Viewer 0.7
Share Files 0.6.2
Text Editor 2.0
Updater 0.6
Video Viewer 0.1.3
Calendar 0.8.0
Gallery+ 14.3.0

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '52476d6fe683a',
  'overwrite.cli.url' => '/owncloud',
  'forcessl' => 'true',
  'datadirectory' => '/home/owncloud/data',
  'appcodechecker' => false,
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'installed' => true,
  'log_type' => 'owncloud',
  'logfile' => 'owncloud.log',
  'loglevel' => 1,
  'logdateformat' => 'd-m-Y H:i:s',
  'logtimezone' => 'Europe/Amsterdam',
  'log_authfailip' => 'true',
  'log_query' => 'false',
  'dbhost' => 'localhost',
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'trusted_domains' =>
  array (
    0 => '10.222.111.109',
    1 => 'llama.mynetgear.com',
    2 => 'llama.mynetgear.com',
    3 => 'llama777.nl',
    4 => 'llama777.nl',
    5 => 'www.llama777.nl',
    6 => '94.211.26.177',
    7 => 'llama.mynetgear.com',
    8 => 'tux300.local',
    9 => 'tux300.lan',
  ),
  'dbname' => 'owncloud',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 
**Operating system:**
windows 8.1
#### Web server error log
```
[Mon Oct 19 22:38:26 2015] [error] [client 10.222.111.1] File does not exist: /var/www/html/favicon.ico, referer: https://llama777.nl/
[Tue Oct 20 21:11:24 2015] [error] [client 10.222.111.148] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/html/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\n#3 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(184): OC\\DB\\Connection->executeUpdate('DELETE FROM `*P...', Array)\n#4 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(189): OC\\Lock\\DBLockingProvider->cleanEmptyLocks()\n#5 [internal function]: OC\\Lock\\DBLockingProvider->__destruct()\n#6 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOExcepti in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53
[Tue Oct 20 21:11:25 2015] [error] [client 10.222.111.148] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/html/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\n#3 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(184): OC\\DB\\Connection->executeUpdate('DELETE FROM `*P...', Array)\n#4 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(189): OC\\Lock\\DBLockingProvider->cleanEmptyLocks()\n#5 [internal function]: OC\\Lock\\DBLockingProvider->__destruct()\n#6 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOExcepti in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53
[Tue Oct 20 21:11:26 2015] [error] [client 10.222.111.1] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/html/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\n#3 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(184): OC\\DB\\Connection->executeUpdate('DELETE FROM `*P...', Array)\n#4 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(189): OC\\Lock\\DBLockingProvider->cleanEmptyLocks()\n#5 [internal function]: OC\\Lock\\DBLockingProvider->__destruct()\n#6 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOExcepti in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53, referer: https://llama777.nl/owncloud/index.php/apps/calendar/
[Tue Oct 20 21:11:26 2015] [error] [client 10.222.111.1] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/html/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\n#3 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(184): OC\\DB\\Connection->executeUpdate('DELETE FROM `*P...', Array)\n#4 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(189): OC\\Lock\\DBLockingProvider->cleanEmptyLocks()\n#5 [internal function]: OC\\Lock\\DBLockingProvider->__destruct()\n#6 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOExcepti in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53
[Tue Oct 20 21:11:56 2015] [error] [client 10.222.111.148] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/html/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\n#3 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(184): OC\\DB\\Connection->executeUpdate('DELETE FROM `*P...', Array)\n#4 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(189): OC\\Lock\\DBLockingProvider->cleanEmptyLocks()\n#5 [internal function]: OC\\Lock\\DBLockingProvider->__destruct()\n#6 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOExcepti in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53
[Tue Oct 20 21:11:57 2015] [error] [client 10.222.111.148] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/html/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\n#3 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(184): OC\\DB\\Connection->executeUpdate('DELETE FROM `*P...', Array)\n#4 /var/www/html/owncloud/lib/private/lock/dblockingprovider.php(189): OC\\Lock\\DBLockingProvider->cleanEmptyLocks()\n#5 [internal function]: OC\\Lock\\DBLockingProvider->__destruct()\n#6 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOExcepti in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53
[Wed Oct 21 09:37:01 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:37:07 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:37:20 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:38:13 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:38:26 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:38:51 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:39:01 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:40:00 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
[Wed Oct 21 09:40:11 2015] [error] [client 10.222.111.168] File does not exist: /var/www/html/owncloud/core/vendor/jquery/jquery-1.10.2.js
```

#### ownCloud log (data/owncloud.log)

```
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#162","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"Jiq7sY9wSjpUNcqvnRY8","remoteAddr":"10.222.111.168","app":"PHP","message":"Undefined index: object_type at \/var\/www\/html\/owncloud\/apps\/activity\/controller\/activities.php#176","level":3,"time":"21-10-2015 09:07:36"}
{"reqId":"we+4n1sful2Xu3p+6s5l","remoteAddr":"10.222.111.168","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'SELECT *  FROM `oc_activity`  WHERE `affecteduser` = ?  AND `type` IN (?,?,?,?,?,?,?) AND `object_type` = ? AND `object_id` = ? ORDER BY `timestamp` DESC LIMIT 30 OFFSET 0' with params [\\\"rachez\\\", \\\"file_created\\\", \\\"file_changed\\\", \\\"file_deleted\\\", \\\"file_restored\\\", \\\"shared\\\", \\\"remote_share\\\", \\\"public_links\\\", \\\"files\\\", 4]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT *  FROM ...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(253): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/data.php(233): OCA\\\\Activity\\\\Data->getActivities(30, 0, ' AND `type` IN ...', Array, Object(OCA\\\\Activity\\\\GroupHelper))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/activity\\\/controller\\\/activities.php(147): OCA\\\\Activity\\\\Data->read(Object(OCA\\\\Activity\\\\GroupHelper), Object(OCA\\\\Activity\\\\UserSettings), 0, 30, 'filter', '', 'files', 4)\\n#5 [internal function]: OCA\\\\Activity\\\\Controller\\\\Activities->fetch(1, 'filter', 'files', 4)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\Activities), 'fetch')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ActivitiesContr...', 'fetch', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"21-10-2015 09:10:01"}
{"reqId":"CVmHMchGwPsG9mK+dLXi","remoteAddr":"10.222.111.168","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"21-10-2015 09:15:24"}
{"reqId":"ClHOQc12hEXbLmNmV6eU","remoteAddr":"10.222.111.168","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"21-10-2015 09:22:51"}
```

#### Browser log
```
Insert your browser log here, this could for example include:
GET 
XHR 
https://10.222.111.109/owncloud/index.php/apps/activity/activities/fetch [HTTP/1.1 500 Internal Server Error 94ms]

**Comment by nickvergessen** [comment]
Okay, few things in the beginning:

> migrate to 8.3

There is no owncloud version 8.3, mind sharing the download link you used?

> click on activities icon of an folder.

Do you mean the Details option in the file list, or which icon are you talking about?
![bildschirmfoto vom 2015-10-21 10 03 37](https://cloud.githubusercontent.com/assets/213943/10631006/2b1a4478-77db-11e5-8e2a-007c12744253.png)

> Should show me the activities of that folder.

This sounds a bit like https://github.com/owncloud/activity/issues/380 Currently folders only show activities that have been performed on them, not activities for files inside the folder. But that's the plan for the future.

> ownCloud log (data/owncloud.log)

The two errors `Undefined index: object_type` and `Column not found: 1054 Unknown column 'object_type' in 'where clause'` sound like the database update of the activity app did not run yet.

**Comment by deanso** [comment]
Youre right, I just migrated to  8.2. Sorry about that.

I mean this icon which I use and correspondig yellow sign:
<img width="1039" alt="2015-10-21 10_24_42-greenshot image editor" src="https://cloud.githubusercontent.com/assets/10999346/10631392/077de7ec-77de-11e5-97ca-a5539261e241.png">

How do I trigger the database update of the activity app: do I have to start over with the whole migration, or can I trigger it separately?

**Comment by nickvergessen** [comment]
Please run the following SQL query:
```sql
SELECT *
FROM `oc_appconfig`
WHERE `appid` = 'activity'
```

Also the question for your download link has not been answered, but is important.

**Comment by deanso** [comment]
+----------+-------------------+-------------+
| appid    | configkey         | configvalue |
+----------+-------------------+-------------+
| activity | enabled           | yes         |
| activity | installed_version | 2.0.2       |
| activity | types             | filesystem  |
+----------+-------------------+-------------+

I used this download link: wget https://download.owncloud.org/community/owncloud-8.2.0.tar.bz2

**Comment by nickvergessen** [comment]
You didn't delete the old files and just uploaded the new files into the existing folder.

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by deanso** [comment]
You're right. Just examined my script and I use rsync to copy them over existing oc.
I'll start again. Thanks for you're help.

**Comment by janusdd** [comment]
Same Problem as described.
But not copied something. 

What I´v tried so far.
 I manually removed my oc_activity SQL tables (rewriting themself by activate activity was my goal --> missed)
Is this issue connected to the wrong version 2.0.2 of the App? where can i manually get an activityapp update?  
sudo -u www-data php occ upgrade brings up  -> latest version

**Comment by nickvergessen** [comment]
Remove the apps/activity/appdata/version file

**Comment by nickvergessen** [comment]
and then run occupgrade

**Comment by janusdd** [comment]
In my case 
owncloud/apps/activity/appinfo/version 
but in dryrun mode i get  a message that  there is an update. So i try, and i suceed thanks for that
