### ISSUE TITLE
Upgrading a 8.1.x install to 8.2.0 breaks shared links

### ISSUE THREAD

**Issue by ricardopadilha** [owncloud/activity#428]
After I updated an 8.1.1 (same for 8.1.3) install to 8.2.0, the shared links stopped working. The install is backed by an sqlite database.

This is the apache log:
```
192.168.5.25 - - [03/Nov/2015:12:13:08 -0800] "GET /index.php/s/PcUsU0jLpQFVo5B HTTP/1.1" 503 6635
```

owncloud.log reports this:
```
{"reqId":"Y+JzZodQ3zEIZc+UdCgS","remoteAddr":"192.168.5.25","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_activity\\\" (\\\"app\\\", \\\"subject\\\", \\\"subjectparams\\\", \\\"message\\\", \\\"messageparams\\\", \\\"file\\\", \\\"link\\\", \\\"user\\\", \\\"affecteduser\\\", \\\"timestamp\\\", \\\"priority\\\", \\\"type\\\", \\\"object_type\\\", \\\"object_id\\\") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\\"files_sharing\\\", \\\"public_shared_file_downloaded\\\", \\\"[\\\\\\\"\\\\\\\\\\\\\\\/ownCloudUserManual.pdf\\\\\\\"]\\\", \\\"\\\", \\\"[]\\\", \\\"\\\\\\\/ownCloudUserManual.pdf\\\", \\\"\\\", null, \\\"ricardo\\\", 1446581991, 30, \\\"public_links\\\", \\\"\\\", 0]:\\n\\nSQLSTATE[HY000]: General error: 1 table oc_activity has no column named object_type\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO \\\"oc...', Array)\\n#2 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/db\\\/connection.php(203): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO \\\"oc...', Array, Array)\\n#3 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\\n#4 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(121): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/apps\\\/activity\\\/lib\\\/data.php(126): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/apps\\\/activity\\\/lib\\\/consumer.php(74): OCA\\\\Activity\\\\Data->send(Object(OC\\\\Activity\\\\Event))\\n#7 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/activitymanager.php(188): OCA\\\\Activity\\\\Consumer->receive(Object(OC\\\\Activity\\\\Event))\\n#8 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/activitymanager.php(215): OC\\\\ActivityManager->publish(Object(OC\\\\Activity\\\\Event))\\n#9 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/apps\\\/files_sharing\\\/lib\\\/controllers\\\/sharecontroller.php(288): OC\\\\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '\\\/ownCloudUserMa...', '', 'ricardo', 'public_links', 30)\\n#10 [internal function]: OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->downloadShare('PcUsU0jLpQFVo5B', NULL, '', '')\\n#11 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#13 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#14 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/public\\\/appframework\\\/app.php(134): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#15 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/core\\\/routes.php(124): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#16 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#17 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(Closure), Array)\\n#18 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/s\\\/PcUsU0jLpQFV...')\\n#19 \\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/index.php(39): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/mnt\\\/DroboFS\\\/Shares\\\/DroboApps\\\/owncloud\\\/app\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":66}","level":3,"time":"2015-11-03T20:19:51+00:00"}
```

This is the schema for `oc_activity` in 8.1.1:
```
sqlite> .schema oc_activity
CREATE TABLE oc_activity (activity_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp INTEGER DEFAULT 0 NOT NULL, priority INTEGER DEFAULT 0 NOT NULL, type VARCHAR(255) NOT NULL COLLATE BINARY, user VARCHAR(64) NOT NULL COLLATE BINARY, affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, app VARCHAR(255) NOT NULL COLLATE BINARY, subject VARCHAR(255) NOT NULL COLLATE BINARY, subjectparams VARCHAR(4000) NOT NULL COLLATE BINARY, message VARCHAR(255) DEFAULT NULL COLLATE BINARY, messageparams VARCHAR(4000) DEFAULT NULL COLLATE BINARY, file VARCHAR(4000) DEFAULT NULL COLLATE BINARY, link VARCHAR(4000) DEFAULT NULL COLLATE BINARY);
CREATE INDEX activity_filter_app ON oc_activity (affecteduser, app, timestamp);
CREATE INDEX activity_filter_by ON oc_activity (affecteduser, user, timestamp);
CREATE INDEX activity_user_time ON oc_activity (affecteduser, timestamp);
```

And in 8.2.0:
```
sqlite> .schema oc_activity
CREATE TABLE "oc_activity" ("activity_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "timestamp" INTEGER DEFAULT 0 NOT NULL, "priority" INTEGER DEFAULT 0 NOT NULL, "type" VARCHAR(255) DEFAULT NULL, "user" VARCHAR(64) DEFAULT NULL, "affecteduser" VARCHAR(64) NOT NULL, "app" VARCHAR(255) NOT NULL, "subject" VARCHAR(255) NOT NULL, "subjectparams" VARCHAR(4000) NOT NULL, "message" VARCHAR(255) DEFAULT NULL, "messageparams" VARCHAR(4000) DEFAULT NULL, "file" VARCHAR(4000) DEFAULT NULL, "link" VARCHAR(4000) DEFAULT NULL, "object_type" VARCHAR(255) DEFAULT NULL, "object_id" INTEGER DEFAULT 0 NOT NULL);
CREATE INDEX activity_user_time ON "oc_activity" ("affecteduser", "timestamp");
CREATE INDEX activity_filter_by ON "oc_activity" ("affecteduser", "user", "timestamp");
CREATE INDEX activity_filter_app ON "oc_activity" ("affecteduser", "app", "timestamp");
```

I performed an `occ upgrade`, but the table schema was not updated.

The schema change was introduced by #363.

**Comment by nickvergessen** [comment]
You didn't update you instance correctly: you did not delete the old files and just uploaded the new files into the existing folder.

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by nickvergessen** [comment]
See #419 #420
