### ISSUE TITLE
Thumbnails of images are not shown in activity menu

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#630]
**Safari 11**
![screen shot 2018-06-29 at 12 54 25](https://user-images.githubusercontent.com/10596560/42089037-fcbeeaee-7b9b-11e8-88be-28d4c76d3299.png)
**Chrome/Firefox**
![screen shot 2018-06-29 at 12 58 33](https://user-images.githubusercontent.com/10596560/42089089-2ad44abe-7b9c-11e8-88f6-59fa41373638.png)

oC 10.0.9.RC2 and activity app branch ```release-2.3.7```

**Comment by DeepDiver1975** [comment]
browser console?
network tab?
server logs?
THX

**Comment by davitol** [comment]
> server logs

```
{"reqId":"e0pfot2yb5v81Y7d1xrr","level":3,"time":"2018-06-29T11:31:25+00:00","remoteAddr":"172.18.0.7","user":"admin","app":"no app in context","method":"GET","url":"\/apps\/activity\/api\/v2\/activity\/all?format=json&previews=true&since=0","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"core_ajax_preview\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(382): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('core_ajax_previ...', Array, 1)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('core_ajax_previ...', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\CachingRouter->generate('core_ajax_previ...', Array)\\n#3 \\\/mnt\\\/data\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(317): OC\\\\URLGenerator->linkToRoute('core_ajax_previ...', Array)\\n#4 \\\/mnt\\\/data\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(241): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->getPreview('admin', 42, '\\\/asdccc-1.txt')\\n#5 \\\/mnt\\\/data\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(181): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->get(Array)\\n#6 \\\/mnt\\\/data\\\/apps\\\/activity\\\/lib\\\/Controller\\\/EndPoint.php(68): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->getFilter(Array)\\n#7 [internal function]: OCA\\\\Activity\\\\Controller\\\\EndPoint->getFilter('all')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\EndPoint), 'getFilter')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\EndPoint), 'getFilter')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('EndPointControl...', 'getFilter', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":113}"}
```



> network tab (mozilla firefox)

![screen shot 2018-06-29 at 13 33 18](https://user-images.githubusercontent.com/10596560/42090306-3a1b11ce-7ba1-11e8-8a24-337dd0401de7.png)

**Comment by davitol** [comment]
It seems to be related to ownCloud 10.0.9.RC code and not to the activity app code. It works fine in oC 10.0.8
