### ISSUE TITLE
Acceptance test restore.feature:269 failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/activity#752]
e.g. https://drone.owncloud.com/owncloud/activity/555/133
```
    And user "user0" has restored the file with original path "textfile0.txt"                                                           # TrashbinContext::elementInTrashIsRestored()
      Exception: TrashbinContext::restoreElement cannot restore from trashbin because no element was found for user user0 at original path textfile0.txt in /var/www/owncloud/server/tests/acceptance/features/bootstrap/TrashbinContext.php:244
      Stack trace:
      #0 /var/www/owncloud/server/tests/acceptance/features/bootstrap/TrashbinContext.php(260): TrashbinContext->restoreElement('user0', 'textfile0.txt')
      #1 [internal function]: TrashbinContext->elementInTrashIsRestored('user0', 'textfile0.txt')
      #2 /var/www/owncloud/server/apps/activity/vendor-bin/behat/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): call_user_func_array(Array, Array)

--- Failed scenarios:

    /var/www/owncloud/server/apps/activity/tests/acceptance/features/webUIActivityDeleteRestore/restore.feature:269

49 scenarios (48 passed, 1 failed)
525 steps (518 passed, 1 failed, 6 skipped)
```

This started being reported after core PR https://github.com/owncloud/core/pull/35906 improved some checks in `restoreElement`  to make sure that restore-from-trashbin steps were actually at least trying to restore something.

**Comment by phil-davis** [comment]
Also see https://drone.owncloud.com/owncloud/activity/555/267
```
--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @When the public downloads the last created file using the webUI
     */
    public function thePublicDownloadsTheLastCreatedFileUsingTheWebui()
    {
        throw new PendingException();
    }

    /**
     * @When the public downloads the last created folder using the webUI
     */
    public function thePublicDownloadsTheLastCreatedFolderUsingTheWebui()
    {
        throw new PendingException();
    }
```
The step text of those needs adjusting to match changes in core yesterday.

**Comment by phil-davis** [comment]
ToDo:
- investigate scenario that ffails on OC 10.2 https://drone.owncloud.com/owncloud/activity/563/280
```
  Scenario: Sharer and sharee check activity after sharee unshares a shared file                                                        # /var/www/owncloud/server/testrunner/apps/activity/tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature:290
    Given these users have been created with default attributes and without skeleton files:                                             # FeatureContext::theseUsersHaveBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
      | username |
      | user1    |
    And user "user0" has shared file "textfile0.txt" with user "user1"                                                                  # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And user "user1" has logged in using the webUI                                                                                      # WebUILoginContext::theUserLogsInUsingTheWebUI()
    And user "user1" has unshared file "textfile0.txt"                                                                                  # FeatureContext::userDeletesFile()
    When the user browses to the activity page                                                                                          # WebUIActivityContext::userHasBrowsedToTheActivityPage()
    Then the activity number 1 should have a message saying that you have unshared file "textfile0.txt" shared by "User Zero" from self # WebUIActivityContext::theActivityNumberShouldHaveAMessageSayingUnsharedFileFromSelf()
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'You unshared textfile0.txt shared by UUser Zero from self'
      +'UUser Zero shared textfile0.txt with you'
    And the activity number 2 should contain message "User Zero shared textfile0.txt with you" in the activity page                     # WebUIActivityContext::theActivityNumberShouldContainMessageInTheActivityPage()
    When the user re-logs in as "user0" using the webUI                                                                                 # WebUILoginContext::theUserRelogsInUsingTheWebUI()
    And the user browses to the activity page                                                                                           # WebUIActivityContext::userHasBrowsedToTheActivityPage()
    Then the activity number 1 should have a message saying that you have shared file "textfile0.txt" with user "User One"              # WebUIActivityContext::theActivityNumberShouldHaveAMessageSayingSharedFolderWithUser()
SCENARIO RESULT: (fail)
```
It has been skipped for now, to get the good things in PR #753 merged.
