### ISSUE TITLE
Could not resolve OCA\\\\Activity\\\\BackgroundJob\\\\EmailNotification

### ISSUE THREAD

**Issue by konstantin-schura** [owncloud/activity#920]
### Steps to reproduce

  -  Migrate owncloud 10.0.1 to docker installation
  -  Update to 10.5.0

### Expected behaviour
owncloud.log without exceptions

### Actual behaviour
Error messages in owncloud.log

    Could not resolve OCA\\Activity\\BackgroundJob\\EmailNotification

### Server configuration
**Operating system**:
Ubuntu 18.04.5 LTS
**Web server:**
Docker container 10.5.0
**Database:**
Mariadb in docker. mariadb Ver 15.1 Distrib 10.4.8-MariaDB
**PHP version:**
PHP 7.4.3
**ownCloud version:** (see ownCloud admin page)
Docker container 10.5.0
**Where did you install ownCloud from:**
Update from 10.0.1
**Signing status (ownCloud 9.0 and above):**

```
/index.php/settings/integrity/failed 
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.3
  - files_pdfviewer: 0.11.2
  - files_sharing: 0.13.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - gallery: 16.1.1
  - market: 0.6.0
  - notifications: 0.5.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - activity
  - activity_backup
  - admin_audit
  - announcementcenter
  - customgroups
  - encryption
  - enterprise_key
  - external
  - files_antivirus
  - files_classifier
  - files_external_dropbox
  - files_external_ftp
  - firewall
  - guests
  - oauth2
  - password_policy
  - ransomware_protection
  - sharepoint
  - systemtags_management
  - theme-enterprise
  - twofactor_totp
  - user_external
  - user_shibboleth
  - windows_network_drive
  - wopi
  - workflow

```

{
"system": {
"apps_paths": [
{
"path": "/var/www/owncloud/apps",
"url": "/apps",
"writable": false
},
{
"path": "/var/www/owncloud/custom",
"url": "/custom",
"writable": true
}
],
"trusted_domains": [
"localhost"
],
"datadirectory": "/mnt/data/files",
"dbtype": "mysql",
"dbhost": "db",
"dbname": "owncloud",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"dbtableprefix": "oc_",
"log_type": "owncloud",
"mail_smtpmode": "smtp",
"mail_smtphost": "REMOVED SENSITIVE VALUE",
"mail_smtpport": "25",
"mail_smtptimeout": 10,
"mail_domain": "REMOVED SENSITIVE VALUE",
"mail_from_address": "REMOVED SENSITIVE VALUE",
"supportedDatabases": [
"sqlite",
"mysql",
"pgsql"
],
"upgrade.disable-web": true,
"default_language": "en",
"overwrite.cli.url": "REMOVED SENSITIVE VALUE",
"htaccess.RewriteBase": "/",
"logfile": "/mnt/data/files/owncloud.log",
"loglevel": 2,
"memcache.local": "\OC\Memcache\APCu",
"mysql.utf8mb4": true,
"filelocking.enabled": true,
"memcache.distributed": "\OC\Memcache\Redis",
"memcache.locking": "\OC\Memcache\Redis",
"redis": {
"host": "redis",
"port": "6379"
},
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"version": "10.5.0.10",
"logtimezone": "UTC",
"installed": true,
"instanceid": "REMOVED SENSITIVE VALUE",
"maintenance": false
}
}

```


**Are you using encryption:** no


#### ownCloud log (data/owncloud.log)
```
{"reqId":"FF7gbfOtJp5CABBwDJPl","level":3,"time":"2021-01-20T09:02:14+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\Activity\\\\BackgroundJob\\\\EmailNotification! Class OCA\\\\Activity\\\\BackgroundJob\\\\EmailNotification does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(110): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(86): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(253): OC\\\\ServerContainer->query()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(340): OC\\\\BackgroundJob\\\\JobList->buildJob()\\n#4 \\\/var\\\/www\\\/owncloud\\\/core\\\/Command\\\/Background\\\/Queue\\\/Status.php(64): OC\\\\BackgroundJob\\\\JobList->listJobs()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(255): OC\\\\Core\\\\Command\\\\Background\\\\Queue\\\\Status->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(1000): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(271): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(147): Symfony\\\\Component\\\\Console\\\\Application->doRun()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(165): Symfony\\\\Component\\\\Console\\\\Application->run()\\n#10 \\\/var\\\/www\\\/owncloud\\\/console.php(116): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":96}"}
```

After update activity can't find BackgroundJob/EmailNotification

MariaDB [owncloud]> select * from oc_jobs;
+--------+---------------------------------------------------+----------+------------+--------------+-------------+--------------------+
| id     | class                                             | argument | last_run   | last_checked | reserved_at | execution_duration |
+--------+---------------------------------------------------+----------+------------+--------------+-------------+--------------------+
|      5 | OCA\Activity\BackgroundJob\ExpireActivities       | null     | 1596560402 |   1611117122 |  1611117122 |                  0 |
|  24305 | OCA\Activity\BackgroundJob\EmailNotification      | null     | 1596617685 |   1611117182 |  1611117182 |                  0 |

Could someone help please?

**Comment by konstantin-schura** [comment]
Upgrade to 10.6 didn't help. 
Maybe someone have any ideas?

**Comment by konstantin-schura** [comment]
fixed.
uninstall and then install activity app.
